#!/bin/sh

# Copyright (C) 2006-2011 Linux Foundation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

if [ -n "$BASH_SOURCE" ]; then
   OEROOT="`dirname $BASH_SOURCE`/layers/oe-core"
elif [ -n "$ZSH_NAME" ]; then
   OEROOT="`dirname $0`/layers/oe-core"
else
   OEROOT="`pwd`/layers/oe-core"
fi

if [ -n "$BBSERVER" ]; then
   unset BBSERVER
fi

if [ -n "$BBSERVER" ]; then
   unset BBSERVER
fi

# Figure out the "TOP" relative to TOP/layers/oe-core
THIS_SCRIPT=`dirname $OEROOT`
THIS_SCRIPT=$THIS_SCRIPT/init-intel-x86-env

if [ -z "$ZSH_NAME" ] && [ "$0" = "$THIS_SCRIPT" -o "$0" = init-intel-x86-env ]; then
   echo "Error: This script needs to be sourced. Please run as '. $THIS_SCRIPT'"
   exit 1
fi

OEROOT=`readlink -f "$OEROOT"`
export OEROOT

TEMPLATECONF=$OEROOT/../../.template-conf
export TEMPLATECONF

S_ARGS="$@"
if [ "$S_ARGS" = "" ] ; then
   S_ARGS=build-intel-x86
fi

. $OEROOT/scripts/oe-buildenv-internal "$S_ARGS" $OEROOT/../bitbake && \
     $OEROOT/scripts/oe-setup-builddir && \
     [ -n "$BUILDDIR" ] && cd $BUILDDIR
if [ $? = 0 ] ; then
   if [ ! -e .configured ] ; then
      perl -p -i -e 's#BBLAYERS \?=#BBLAYERS =#' conf/bblayers.conf

      	   for e in wrlabs-integration \
	       wr-kernel \
	       meta-intel \
	       meta-intel/meta-isg/meta-valleyisland \
	       wr-base \
	       wr-fixes \
	       wr-tools-debug \
	       wrll-hac \
	       pulsar \
	       meta-gateway \
	       meta-overc/meta-cube \
	       meta-cloud-services \
               meta-browser \
               meta-openembedded/meta-filesystems \
	       meta-openembedded/meta-networking \
	       meta-openembedded/meta-gnome \
	       meta-openembedded/meta-oe \
	       meta-openembedded/meta-python \
	       meta-openembedded/meta-perl \
	       meta-openembedded/meta-webserver \
	       meta-openembedded/meta-xfce \
	       meta-virtualization \
	       oe-meta-go ; do
	       if [ -e $OEROOT/../$e ] ; then
    		   perl -p -i -e "s#^(.*)oe-core/meta(.*)#\$1oe-core/meta\$2\n\$1$e \\\\#" conf/bblayers.conf
	       fi
      done
      perl -p -i -e 's#^(.*)oe-core/meta(.*)#$1wrlinux \\\n$1oe-core/meta$2#' conf/bblayers.conf

      cat<<EOF>>conf/local.conf
DISTRO = "wrlinux-small"
WRLINUX_RCPLVERSION = ".10"
MACHINE = "intel-corei7-64"
# Set wide compatibility with core2 processors
DEFAULTTUNE = "core2-64"
COMPATIBLE_MACHINE_intel-corei7-64 = "${MACHINE}"
# Set default machine to select in the hob interface
HOB_MACHINE = "intel-corei7-64"
DEFAULT_IMAGE = "wrlinux-image-glibc-small"
LINUX_KERNEL_TYPE = "standard"
PREFERRED_PROVIDER_virtual/kernel_intel-corei7-64 = "linux-yocto"
KTYPE_ENABLED = "standard"
PACKAGE_CLASSES = "package_rpm"
# Activate systemd
VIRTUAL-RUNTIME_init_manager = " systemd "
DISTRO_FEATURES_append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += " sysvinit "
KERNEL_FEATURES_append = " cfg/systemd.scc"
USER_CLASSES = "buildstats buildstats-summary"
IMAGE_CLASSES += "image-export-vars"
IMAGE_FSTYPES += "tar.bz2"
NOISO = "1"
IMAGE_FSTYPES += "ext3"
IMAGE_FSTYPES += "live"

EXTRA_IMAGEDEPENDS += "\${@base_contains('INCOMPATIBLE_LICENSE', 'GPLv3', '', 'grub-efi', d)}"

## Included feature templates
require `pwd`/../layers/wr-kernel/templates/default/template.conf
require `pwd`/../layers/wr-base/templates/default/template.conf
require `pwd`/../layers/meta-gateway/templates/default/template.conf
require `pwd`/../layers/wrlabs-integration/templates/default/template.conf

# Kernel overrides
INHERIT += "blacklist"
PNBLACKLIST[linux-windriver] = "Recipe not buildable without local kernel git"
PNBLACKLIST[linux-windriver-dummy] = "Recipe not buildable without local kernel git"
# Unblacklist the YP kernel
PNBLACKLIST[linux-yocto] = ""
PNBLACKLIST[linux-yocto-rt] = ""
PNBLACKLIST[linux-yocto-tiny] = ""
SRC_URI_pn-kern-tools-native = "git://git.yoctoproject.org/yocto-kernel-tools.git"
# EXTRA_BBMASK may be appended in a layer or template
BBMASK = "/(NO_MATCH/\${EXTRA_BBMASK})"

PREFERRED_VERSION_linux-yocto = "3.14%"
PREFERRED_VERSION_linux-yocto-rt = "3.14%"

DL_DIR = "\${TOPDIR}/../downloads"
SSTATE_DIR = "\${TOPDIR}/../sstate-cache"

EOF
      touch .configured
   fi
fi
unset OEROOT
unset BBPATH
unset THIS_SCRIPT
unset S_ARGS
unset TEMPLATECONF
